Add script to reconfigure AFCv3.1 and AFCv4.0 FPGA via XVC
lnls-sirius/scripts pull request #173
Opened 2024-12-18 17:04 UTC by augustofg

This script assumes that openocd with XVC support is installed and in PATH.

2024-12-19 17:22 UTC, gustavosr8 commented
Have you tested it? I don't really understand the `scansta` and `boot` commands (maybe it would be nice to add a comment explaining them), but the bash part seems good to me.

2024-12-19 17:38 UTC, augustofg commented
> Have you tested it? I don't really understand the `scansta` and `boot` commands (maybe it would be nice to add a comment explaining them), but the bash part seems good to me.

Yes, I've tested it. The `scansta` SVF file contains the JTAG commands to change the SCANSTA111 JTAG switch to select the FPGA (necessary for AFCv3.1 cards). The `boot` SVF file has the JTAG commands to make the FPGA reconfigure itself from the non-volatile SPI flash.

2025-01-06 15:04 UTC, ericonr requested changes

2025-01-06 15:04 UTC, ericonr commented on bin/sirius-script-afc-boot-from-flash.sh
> +	scansta_cmd=""
Put these items in the same order in both branches, so it's clearer what each version is using and leaving empty.

2025-01-07 12:31 UTC, augustofg commented on bin/sirius-script-afc-boot-from-flash.sh
> +fi
Well, from my understanding this script won't be used directly by the operators, but called by `sirius-script-rabpm-mngr.py`, so I would prefer keeping the afcv3/afcv4-sfp board name. Ideally, it would be possible to scan the JTAG chain and create a correct device map on the fly, but it seems that `openocd` doesn't support this.

2025-01-07 12:31 UTC, augustofg commented on bin/sirius-script-afc-boot-from-flash.sh
> +	scansta_cmd=""
Done.

2025-01-07 12:45 UTC, ericonr commented on bin/sirius-script-afc-boot-from-flash.sh
> +fi
My bad, I had forgotten we would have another script.

Fair enough!

2025-01-07 21:24 UTC, anacso17 approved these changes

2025-01-07 22:04 UTC, ericonr reviewed
It would be nice to document in the commit that this was based on the scripts from fpga-programming, and also explain why it diverges in some points.

The `FREQUENCY` in the svf scripts is different, the `sfp_jtag` line as well, and some further device properties (though part of those could have been folded into `cpld/xilinx-xc7.cfg`?)

2025-01-13 21:33 UTC, ericonr commented
As discussed, the scripts from `fpga-programming` will be updated to match the ones here.

2025-01-16 12:19 UTC, augustofg commented
`FREQUENCY` command removed from SVF files.

2025-01-27 18:26 UTC, ericonr approved these changes

2025-01-28 11:14 UTC, gustavosr8 approved these changes

2025-01-31 17:43 UTC, merged